name: "Integration Tests"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [12.x]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2.1.5
        with:
            node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: xvfb-run -a npm run test-client-integration
        if: runner.os == 'Linux'
      - run: npm  run test-client-integration
        if: runner.os != 'Linux'
